import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { PROBE_PREFIX, parseSetup, parseInspect, verifySetup, verifyRestart, verifyDeniedPolicy } from '../scripts/worker-protocol.js';
import { runCommand } from '../scripts/worker-command.js';

// The original observed record is a regression input, not an oracle generated by our validator.
const baseline = JSON.parse(readFileSync(new URL('../docs/worker-rehearsal-results.json', import.meta.url), 'utf8'));
const frame = (value: unknown) => PROBE_PREFIX + JSON.stringify(value);
const setup = () => {
  const value = structuredClone(baseline.worker0);
  value.sessionMarker = value.marker;
  value.mounts = value.mounts.map((m: { path: string }) => ({ ...m, options: m.path === '/etc/resolv.conf' ? 'ro,relatime' : 'rw,relatime' }));
  return value;
};
const inspect = (which: 'beforeStop' | 'afterRestart') => {
  const value = structuredClone(baseline[which]); value.sessionMarker = value.marker;
  // A valid reference independent of the original fixture's empty/truncated read.
  if (which === 'beforeStop') value.heartbeatAfter = String(Number(value.heartbeatBefore) + 100);
  return value;
};

test('worker rehearsal requires exactly one framed, complete record', () => {
  const value = setup(); verifySetup(parseSetup(frame(value)), value.marker);
  for (const output of ['', '{}', frame(value) + '\n' + frame(value), frame(value) + '\nunexpected output']) assert.throws(() => parseSetup(output));
  for (const field of ['boot', 'heartbeat', 'runtime', 'observations', 'sessionMarker']) {
    const bad = setup(); delete bad[field]; assert.throws(() => parseSetup(frame(bad)), field);
  }
});

test('missing, empty, extra or false observation inventories cannot pass', () => {
  for (const mutate of [
    (v: any) => { v.observations = {}; },
    (v: any) => { delete v.observations.hostSentinelUnreadable; },
    (v: any) => { v.observations.hostSentinelUnreadable = false; },
    (v: any) => { v.observations.newUntestedClaim = true; },
  ]) { const value = setup(); mutate(value); assert.throws(() => verifySetup(parseSetup(frame(value)), value.marker)); }
});

test('network command errors and contradictory pass booleans cannot prove policy enforcement', () => {
  for (const mutate of [
    (v: any) => { v.directTls.code = 28; }, // Timeout can be an outage.
    (v: any) => { v.directHttp.code = null; },
    (v: any) => { v.networks[0].output = '200'; },
    (v: any) => { v.networks[0].name = v.networks[1].name; },
    (v: any) => { v.mounts.find((m: any) => m.path === '/etc/resolv.conf').options = 'rw'; },
    (v: any) => { v.runtime.cpus = 16; },
  ]) { const value = setup(); mutate(value); assert.throws(() => verifySetup(parseSetup(frame(value)), value.marker)); }
  assert.throws(() => verifyDeniedPolicy({})); assert.throws(() => verifyDeniedPolicy({ allowed: true }));
  assert.equal(verifyDeniedPolicy({ allowed: false, reason: 'explicit denial' }).allowed, false);
});

test('missing heartbeat or session files cannot make a restart pass by comparing nulls', () => {
  const before = parseInspect(frame(inspect('beforeStop'))), after = parseInspect(frame(inspect('afterRestart')));
  verifyRestart(before, after);
  for (const field of ['marker', 'sessionMarker', 'boot', 'heartbeatBefore', 'heartbeatAfter', 'dockerId']) {
    const missing = inspect('afterRestart'); missing[field] = null;
    assert.throws(() => parseInspect(frame(missing)), field);
  }
  assert.throws(() => verifyRestart(before, { ...after, boot: before.boot }));
  assert.throws(() => verifyRestart(before, { ...after, heartbeatAfter: String(Number(after.heartbeatBefore) + 1) }));
  assert.throws(() => verifyRestart(before, { ...after, sessionMarker: 'another worker' }));
  assert.throws(() => parseInspect(frame({ ...inspect('beforeStop'), heartbeatAfter: '' })), 'The original truncated heartbeat must be rejected');
});

test('worker command client counts stderr in output limits and fails before spawning on cancellation', async () => {
  const result = await runCommand(process.execPath, ['-e', "setInterval(()=>process.stderr.write('x'.repeat(8192)),1)"], { outputBytes: 4096, timeoutMs: 2000 });
  assert.equal(result.stopped, 'output-limit'); assert.ok(Buffer.byteLength(result.stderr) <= 4096);
  const aborted = await runCommand('/does-not-exist', [], { signal: AbortSignal.abort() });
  assert.equal(aborted.stopped, 'aborted');
  const missing = await runCommand('/does-not-exist', []); assert.equal(missing.stopped, 'spawn-error');
});

test('worker command deadline closes pipes and kills wrapper descendants', async () => {
  const dir = mkdtempSync(join(tmpdir(), 'collective-worker-client-')), pidFile = join(dir, 'child.pid');
  let pid: number | undefined;
  try {
    const script = join(dir, 'wrapper.cjs');
    writeFileSync(script, `const {spawn}=require('node:child_process'); const fs=require('node:fs');
      const child=spawn(process.execPath,['-e',"process.stdout.write('ready');setInterval(()=>{},1000)"],{stdio:['ignore','inherit','inherit']});
      fs.writeFileSync(${JSON.stringify(pidFile)},String(child.pid)); setInterval(()=>{},1000);`);
    const started = Date.now();
    const result = await runCommand(process.execPath, [script], { timeoutMs: 800 });
    assert.equal(result.stopped, 'timeout'); assert.match(result.stdout, /ready/); assert.ok(Date.now() - started < 3000);
    pid = Number(readFileSync(pidFile, 'utf8'));
    const alive = () => { try { process.kill(pid!, 0); return true; } catch { return false; } };
    for (let i = 0; i < 20 && alive(); i++) await new Promise(done => setTimeout(done, 50));
    assert.equal(alive(), false);
  } finally { if (pid) { try { process.kill(pid, 'SIGKILL'); } catch {} } rmSync(dir, { recursive: true, force: true }); }
});
