export type Mode = 'live' | 'simulation';
export interface MissionScope { missionId?: string; missionRevision?: number }
export interface Agent { id: string; name: string; role: string; color: string; avatar: string; bio: string; roomId: string; status: 'idle' | 'working' | 'waiting' | 'paused'; sessionId?: string; completed: number; createdAt: string }
export interface Room { id: string; name: string; purpose: string; icon: string; channelId?: string; discordCursor?: string; createdAt: string }
export interface Mission { id: string; title: string; brief: string; criteria: string[]; status: 'draft' | 'active' | 'paused' | 'complete'; revision: number; createdAt: string }
export interface Task { id: string; missionId: string; version?: number; reviewRound?: number; criteriaId?: string; submissionId?: string; title: string; description: string; ownerId: string; status: 'todo' | 'doing' | 'review' | 'done' | 'blocked'; dependencies: string[]; acceptance: string; evidence: string[]; review?: { reviewerId: string; accepted: boolean; note: string; at: string; evaluationId?: string }; createdAt: string }
export interface Message extends MissionScope { id: string; roomId: string; authorId: string; authorName: string; content: string; recipients: string[]; delivery: 'pending' | 'delivered' | 'failed'; discordId?: string; replyTo?: string; depth: number; createdAt: string }
export interface Knowledge { id: string; title: string; content: string; kind: 'fact' | 'hypothesis' | 'decision' | 'question'; sources: string[]; authorId: string; revision: number; previousId?: string; createdAt: string }
export interface Artifact { id: string; title: string; description: string; path: string; authorId: string; taskId?: string; mime: string; sha256: string; size: number; createdAt: string }
export interface Meeting extends MissionScope { id: string; title: string; agenda: string; expectedOutcome: string; roomId: string; participants: string[]; startsAt: string; endsAt: string; status: 'scheduled' | 'active' | 'complete'; outcome?: string; createdAt: string }
export type Capability = 'github.create_repo' | 'github.create_pr' | 'deploy.preview' | 'team.add_agent' | 'environment.add_room' | 'tool.install' | 'external.publish' | 'money.spend' | 'human.contact' | 'resource.other';
export interface PermissionRequest extends MissionScope { id: string; agentId: string; title: string; reason: string; capability: Capability; scope: Record<string, unknown>; alternatives: string; estimatedCost: number; status: 'pending' | 'approved' | 'denied' | 'revoked' | 'fulfilled'; decisionNote?: string; decidedBy?: string; decidedAt?: string; expiresAt?: string; taskId?: string; result?: unknown; createdAt: string }
export interface Job extends MissionScope { id: string; agentId: string; kind: 'mission' | 'task' | 'message' | 'meeting' | 'feedback' | 'permission' | 'continue'; payload: Record<string, unknown>; dedupeKey: string; status: 'pending' | 'running' | 'done' | 'failed' | 'cancelled'; attempts: number; availableAt: string; claimedAt?: string; error?: string; createdAt: string }
export interface Run { id: string; agentId: string; jobId: string; attempt?: number; status: 'running' | 'complete' | 'failed' | 'interrupted'; sessionId?: string; summary?: string; error?: string; inputTokens: number; outputTokens: number; estimatedCost: number; turns: number; startedAt: string; endedAt?: string }
export interface Outbox { id: string; kind: 'message' | 'request' | 'artifact' | 'notice'; entityId: string; roomId: string; status: 'pending' | 'sending' | 'sent' | 'failed'; attempts: number; nextAttemptAt: string; discordId?: string; error?: string; createdAt: string }
export interface Quota { id: string; fiveHourUsed?: number; weeklyUsed?: number; fiveHourReset?: string; weeklyReset?: string; extraUsageEnabled?: boolean; observedAt: string; source: 'provider' | 'operator'; }
export interface Settings { id: 'settings'; paused: boolean; timezone: string; weekdays: number[]; startHour: number; endHour: number; maxConcurrent: number; maxTurnsPerRun: number; maxRunsPerDay: number; maxRunSeconds: number; quotaStopPercent: number; quotaMaxAgeMinutes: number; model: string; theme: 'office' | 'ship' | 'castle'; maxAgents: number; maxConversationDepth: number; demoStep: number; }
export interface Event { id: number; type: string; actorId: string; entityId?: string; data: unknown; createdAt: string }
export interface Collections { agents: Agent; rooms: Room; missions: Mission; tasks: Task; messages: Message; knowledge: Knowledge; artifacts: Artifact; meetings: Meeting; requests: PermissionRequest; jobs: Job; runs: Run; outbox: Outbox; quotas: Quota; settings: Settings }
export type Collection = keyof Collections;
export interface RuntimeStatus { mode: Mode; discord: 'unconfigured' | 'connecting' | 'connected' | 'error'; discordError?: string; claude: 'unknown' | 'available' | 'missing' | 'unauthenticated'; activeRuns: number; blockReason?: string; nextOpen?: string; }
